name: Run Test

on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"

      - name: Install cv_expt in editable mode
        run: |
          pip install -e .

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coveralls coverage

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest --cov=cv_expt

      - name: Run tests with coverage
        run: |
          coverage run --source=cv_expt -m pytest tests/ 

      - name: Upload coverage to Coveralls
        run: |
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.CV_EXPT }}
          COVERALLS_SERVICE_NAME: "github-actions"